/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CategoryRouteImport } from './routes/$category'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategoryIndexRouteImport } from './routes/$category.index'
import { Route as CategoryDetailRouteImport } from './routes/$category.detail'

const CategoryRoute = CategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryIndexRoute = CategoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CategoryRoute,
} as any)
const CategoryDetailRoute = CategoryDetailRouteImport.update({
  id: '/detail',
  path: '/detail',
  getParentRoute: () => CategoryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$category': typeof CategoryRouteWithChildren
  '/$category/detail': typeof CategoryDetailRoute
  '/$category/': typeof CategoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$category/detail': typeof CategoryDetailRoute
  '/$category': typeof CategoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$category': typeof CategoryRouteWithChildren
  '/$category/detail': typeof CategoryDetailRoute
  '/$category/': typeof CategoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$category' | '/$category/detail' | '/$category/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$category/detail' | '/$category'
  id: '__root__' | '/' | '/$category' | '/$category/detail' | '/$category/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoryRoute: typeof CategoryRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$category': {
      id: '/$category'
      path: '/$category'
      fullPath: '/$category'
      preLoaderRoute: typeof CategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$category/': {
      id: '/$category/'
      path: '/'
      fullPath: '/$category/'
      preLoaderRoute: typeof CategoryIndexRouteImport
      parentRoute: typeof CategoryRoute
    }
    '/$category/detail': {
      id: '/$category/detail'
      path: '/detail'
      fullPath: '/$category/detail'
      preLoaderRoute: typeof CategoryDetailRouteImport
      parentRoute: typeof CategoryRoute
    }
  }
}

interface CategoryRouteChildren {
  CategoryDetailRoute: typeof CategoryDetailRoute
  CategoryIndexRoute: typeof CategoryIndexRoute
}

const CategoryRouteChildren: CategoryRouteChildren = {
  CategoryDetailRoute: CategoryDetailRoute,
  CategoryIndexRoute: CategoryIndexRoute,
}

const CategoryRouteWithChildren = CategoryRoute._addFileChildren(
  CategoryRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoryRoute: CategoryRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
